# Exported from Render on 2025-05-28T19:58:20Z (ou a data do seu export)
services:
- type: web
  name: cadastro_web_render # Nome do seu serviço no Render
  runtime: python
  repo: https://github.com/AMS2025-phm/cadastro_web_render # O URL do seu repositório Git
  plan: free # Ou starter/pro, dependendo do seu plano
  region: oregon # A região onde seu serviço será implantado
  buildCommand: pip install -r requirements.txt # Comando para instalar dependências
  startCommand: gunicorn app:app # Comando para iniciar a aplicação Flask com Gunicorn
  autoDeployTrigger: commit # Isso garante que um novo deploy seja acionado em cada commit
version: "1"